export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      <body style={{backgroundColor: '#2d2d2d'}}>
        {children}
      </body>
    </html>
  )
}
